/**
 * @fileOverview 错误常量 - 企业级Agent框架的错误代码和错误消息定义
 * @module constants/errors
 * @description 定义框架内所有错误相关的常量，包括HTTP状态码、错误代码前缀、各类错误码定义等
 */

/**
 * HTTP状态码常量
 * 用于标准化HTTP请求响应的状态标识
 */
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511,
} as const;

/**
 * 错误代码前缀常量
 * 用于组织错误代码的分类标识
 */
export const ERROR_PREFIX = {
  GENERAL: 'ERR_',
  MODEL: 'ERR_MODEL_',
  TOOL: 'ERR_TOOL_',
  EXECUTION: 'ERR_EXEC_',
  AUTH: 'ERR_AUTH_',
  RATE_LIMIT: 'ERR_RATE_',
  TIMEOUT: 'ERR_TIMEOUT_',
  VALIDATION: 'ERR_VALIDATION_',
  CONFIG: 'ERR_CONFIG_',
  CIRCUIT_BREAKER: 'ERR_CB_',
  RETRY: 'ERR_RETRY_',
  NETWORK: 'ERR_NET_',
  STORAGE: 'ERR_STORAGE_',
  SECURITY: 'ERR_SEC_',
  MIDDLEWARE: 'ERR_MW_',
  PLUGIN: 'ERR_PLUGIN_',
} as const;

/**
 * 模型相关错误代码
 * 错误代码格式：ERR_MODEL_XXX，其中XXX为三位数字序号
 */
export const MODEL_ERRORS = {
  MODEL_NOT_FOUND: `${ERROR_PREFIX.MODEL}001`,
  MODEL_NOT_SUPPORTED: `${ERROR_PREFIX.MODEL}002`,
  MODEL_INVOCATION_FAILED: `${ERROR_PREFIX.MODEL}003`,
  MODEL_RESPONSE_FORMAT_ERROR: `${ERROR_PREFIX.MODEL}004`,
  MODEL_CONTEXT_LENGTH_EXCEEDED: `${ERROR_PREFIX.MODEL}005`,
  MODEL_RATE_LIMIT_EXCEEDED: `${ERROR_PREFIX.MODEL}006`,
  MODEL_API_KEY_INVALID: `${ERROR_PREFIX.MODEL}007`,
  MODEL_API_KEY_MISSING: `${ERROR_PREFIX.MODEL}008`,
  MODEL_TIMEOUT: `${ERROR_PREFIX.MODEL}009`,
  MODEL_QUOTA_EXCEEDED: `${ERROR_PREFIX.MODEL}010`,
  MODEL_INVALID_PARAMETERS: `${ERROR_PREFIX.MODEL}011`,
  MODEL_UNAUTHORIZED: `${ERROR_PREFIX.MODEL}012`,
  MODEL_FORBIDDEN: `${ERROR_PREFIX.MODEL}013`,
  MODEL_SERVER_ERROR: `${ERROR_PREFIX.MODEL}014`,
  MODEL_SERVICE_UNAVAILABLE: `${ERROR_PREFIX.MODEL}015`,
} as const;

/**
 * 工具相关错误代码
 * 错误代码格式：ERR_TOOL_XXX，其中XXX为三位数字序号
 */
export const TOOL_ERRORS = {
  TOOL_NOT_FOUND: `${ERROR_PREFIX.TOOL}001`,
  TOOL_NOT_AVAILABLE: `${ERROR_PREFIX.TOOL}002`,
  TOOL_EXECUTION_FAILED: `${ERROR_PREFIX.TOOL}003`,
  TOOL_VALIDATION_FAILED: `${ERROR_PREFIX.TOOL}004`,
  TOOL_TIMEOUT: `${ERROR_PREFIX.TOOL}005`,
  TOOL_PERMISSION_DENIED: `${ERROR_PREFIX.TOOL}006`,
  TOOL_INVALID_PARAMETERS: `${ERROR_PREFIX.TOOL}007`,
  TOOL_NOT_INITIALIZED: `${ERROR_PREFIX.TOOL}008`,
  TOOL_ALREADY_REGISTERED: `${ERROR_PREFIX.TOOL}009`,
  TOOL_DEPENDENCY_MISSING: `${ERROR_PREFIX.TOOL}010`,
  TOOL_DEPENDENCY_CIRCULAR: `${ERROR_PREFIX.TOOL}011`,
  TOOL_CONFIGURATION_ERROR: `${ERROR_PREFIX.TOOL}012`,
  TOOL_RESOURCE_EXHAUSTED: `${ERROR_PREFIX.TOOL}013`,
  TOOL_CONCURRENT_LIMIT_EXCEEDED: `${ERROR_PREFIX.TOOL}014`,
} as const;

/**
 * 执行相关错误代码
 * 错误代码格式：ERR_EXEC_XXX，其中XXX为三位数字序号
 */
export const EXECUTION_ERRORS = {
  EXECUTION_TIMEOUT: `${ERROR_PREFIX.EXECUTION}001`,
  EXECUTION_CANCELLED: `${ERROR_PREFIX.EXECUTION}002`,
  EXECUTION_STEPS_EXCEEDED: `${ERROR_PREFIX.EXECUTION}003`,
  EXECUTION_INFINITE_LOOP: `${ERROR_PREFIX.EXECUTION}004`,
  EXECUTION_CONTEXT_EXPIRED: `${ERROR_PREFIX.EXECUTION}005`,
  EXECUTION_MEMORY_EXCEEDED: `${ERROR_PREFIX.EXECUTION}006`,
  EXECUTION_INVALID_STATE: `${ERROR_PREFIX.EXECUTION}007`,
  EXECUTION_INTERRUPTED: `${ERROR_PREFIX.EXECUTION}008`,
  EXECUTION_DEPTH_EXCEEDED: `${ERROR_PREFIX.EXECUTION}009`,
  EXECUTION_TOKEN_LIMIT_EXCEEDED: `${ERROR_PREFIX.EXECUTION}010`,
  EXECUTION_PLAN_INVALID: `${ERROR_PREFIX.EXECUTION}011`,
  EXECUTION_PLAN_FAILED: `${ERROR_PREFIX.EXECUTION}012`,
  EXECUTION_RESULT_INVALID: `${ERROR_PREFIX.EXECUTION}013`,
  EXECUTION_AGENT_NOT_READY: `${ERROR_PREFIX.EXECUTION}014`,
  EXECUTION_SESSION_EXPIRED: `${ERROR_PREFIX.EXECUTION}015`,
} as const;

/**
 * 认证授权相关错误代码
 * 错误代码格式：ERR_AUTH_XXX，其中XXX为三位数字序号
 */
export const AUTH_ERRORS = {
  AUTH_FAILED: `${ERROR_PREFIX.AUTH}001`,
  AUTH_TOKEN_EXPIRED: `${ERROR_PREFIX.AUTH}002`,
  AUTH_TOKEN_INVALID: `${ERROR_PREFIX.AUTH}003`,
  AUTH_TOKEN_MISSING: `${ERROR_PREFIX.AUTH}004`,
  AUTH_INSUFFICIENT_PERMISSIONS: `${ERROR_PREFIX.AUTH}005`,
  AUTH_USER_NOT_FOUND: `${ERROR_PREFIX.AUTH}006`,
  AUTH_USER_DISABLED: `${ERROR_PREFIX.AUTH}007`,
  AUTH_ACCOUNT_LOCKED: `${ERROR_PREFIX.AUTH}008`,
  AUTH_PASSWORD_EXPIRED: `${ERROR_PREFIX.AUTH}009`,
  AUTH_PASSWORD_INVALID: `${ERROR_PREFIX.AUTH}010`,
  AUTH_SESSION_EXPIRED: `${ERROR_PREFIX.AUTH}011`,
  AUTH_SESSION_INVALID: `${ERROR_PREFIX.AUTH}012`,
  AUTH_CREDENTIALS_EXPIRED: `${ERROR_PREFIX.AUTH}013`,
  AUTH_PROVIDER_UNAVAILABLE: `${ERROR_PREFIX.AUTH}014`,
  AUTH_MFA_REQUIRED: `${ERROR_PREFIX.AUTH}015`,
  AUTH_MFA_INVALID: `${ERROR_PREFIX.AUTH}016`,
} as const;

/**
 * 速率限制相关错误代码
 * 错误代码格式：ERR_RATE_XXX，其中XXX为三位数字序号
 */
export const RATE_LIMIT_ERRORS = {
  RATE_LIMIT_EXCEEDED: `${ERROR_PREFIX.RATE_LIMIT}001`,
  TOKEN_LIMIT_EXCEEDED: `${ERROR_PREFIX.RATE_LIMIT}002`,
  QUOTA_EXCEEDED: `${ERROR_PREFIX.RATE_LIMIT}003`,
  CONCURRENT_LIMIT_EXCEEDED: `${ERROR_PREFIX.RATE_LIMIT}004`,
  DAILY_LIMIT_EXCEEDED: `${ERROR_PREFIX.RATE_LIMIT}005`,
  MONTHLY_LIMIT_EXCEEDED: `${ERROR_PREFIX.RATE_LIMIT}006`,
  RATE_LIMIT_WINDOW_NOT_STARTED: `${ERROR_PREFIX.RATE_LIMIT}007`,
  RATE_LIMIT_BACKOFF_REQUIRED: `${ERROR_PREFIX.RATE_LIMIT}008`,
} as const;

/**
 * 超时相关错误代码
 * 错误代码格式：ERR_TIMEOUT_XXX，其中XXX为三位数字序号
 */
export const TIMEOUT_ERRORS = {
  REQUEST_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}001`,
  RESPONSE_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}002`,
  IDLE_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}003`,
  OPERATION_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}004`,
  SESSION_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}005`,
  CONNECTION_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}006`,
  READ_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}007`,
  WRITE_TIMEOUT: `${ERROR_PREFIX.TIMEOUT}008`,
} as const;

/**
 * 验证相关错误代码
 * 错误代码格式：ERR_VALIDATION_XXX，其中XXX为三位数字序号
 */
export const VALIDATION_ERRORS = {
  VALIDATION_FAILED: `${ERROR_PREFIX.VALIDATION}001`,
  VALIDATION_SCHEMA_INVALID: `${ERROR_PREFIX.VALIDATION}002`,
  VALIDATION_TYPE_MISMATCH: `${ERROR_PREFIX.VALIDATION}003`,
  VALIDATION_REQUIRED_FIELD_MISSING: `${ERROR_PREFIX.VALIDATION}004`,
  VALIDATION_CONSTRAINT_VIOLATED: `${ERROR_PREFIX.VALIDATION}005`,
  VALIDATION_FORMAT_INVALID: `${ERROR_PREFIX.VALIDATION}006`,
  VALIDATION_RANGE_EXCEEDED: `${ERROR_PREFIX.VALIDATION}007`,
  VALIDATION_PATTERN_NOT_MATCHED: `${ERROR_PREFIX.VALIDATION}008`,
} as const;

/**
 * 配置相关错误代码
 * 错误代码格式：ERR_CONFIG_XXX，其中XXX为三位数字序号
 */
export const CONFIG_ERRORS = {
  CONFIG_NOT_FOUND: `${ERROR_PREFIX.CONFIG}001`,
  CONFIG_INVALID: `${ERROR_PREFIX.CONFIG}002`,
  CONFIG_LOAD_FAILED: `${ERROR_PREFIX.CONFIG}003`,
  CONFIG_MERGE_FAILED: `${ERROR_PREFIX.CONFIG}004`,
  CONFIG_REQUIRED_FIELD_MISSING: `${ERROR_PREFIX.CONFIG}005`,
  CONFIG_TYPE_MISMATCH: `${ERROR_PREFIX.CONFIG}006`,
  CONFIG_ENV_VAR_NOT_SET: `${ERROR_PREFIX.CONFIG}007`,
  CONFIG_FILE_NOT_FOUND: `${ERROR_PREFIX.CONFIG}008`,
  CONFIG_FILE_PARSE_ERROR: `${ERROR_PREFIX.CONFIG}009`,
} as const;

/**
 * 断路器相关错误代码
 * 错误代码格式：ERR_CB_XXX，其中XXX为三位数字序号
 */
export const CIRCUIT_BREAKER_ERRORS = {
  CIRCUIT_BREAKER_OPEN: `${ERROR_PREFIX.CIRCUIT_BREAKER}001`,
  CIRCUIT_BREAKER_HALF_OPEN: `${ERROR_PREFIX.CIRCUIT_BREAKER}002`,
  CIRCUIT_BREAKER_CLOSED: `${ERROR_PREFIX.CIRCUIT_BREAKER}003`,
  CIRCUIT_BREAKER_ERROR_THRESHOLD_EXCEEDED: `${ERROR_PREFIX.CIRCUIT_BREAKER}004`,
  CIRCUIT_BREAKER_FORCED_OPEN: `${ERROR_PREFIX.CIRCUIT_BREAKER}005`,
} as const;

/**
 * 重试相关错误代码
 * 错误代码格式：ERR_RETRY_XXX，其中XXX为三位数字序号
 */
export const RETRY_ERRORS = {
  RETRY_EXHAUSTED: `${ERROR_PREFIX.RETRY}001`,
  RETRY_NOT_ALLOWED: `${ERROR_PREFIX.RETRY}002`,
  RETRY_BACKOFF_FAILED: `${ERROR_PREFIX.RETRY}003`,
  RETRY_INTERRUPTED: `${ERROR_PREFIX.RETRY}004`,
} as const;

/**
 * 网络相关错误代码
 * 错误代码格式：ERR_NET_XXX，其中XXX为三位数字序号
 */
export const NETWORK_ERRORS = {
  NETWORK_ERROR: `${ERROR_PREFIX.NETWORK}001`,
  CONNECTION_REFUSED: `${ERROR_PREFIX.NETWORK}002`,
  CONNECTION_RESET: `${ERROR_PREFIX.NETWORK}003`,
  NETWORK_UNREACHABLE: `${ERROR_PREFIX.NETWORK}004`,
  HOST_UNREACHABLE: `${ERROR_PREFIX.NETWORK}005`,
  PORT_UNREACHABLE: `${ERROR_PREFIX.NETWORK}006`,
  SOCKET_TIMEOUT: `${ERROR_PREFIX.NETWORK}007`,
  DNS_LOOKUP_FAILED: `${ERROR_PREFIX.NETWORK}008`,
  SSL_ERROR: `${ERROR_PREFIX.NETWORK}009`,
  CERTIFICATE_ERROR: `${ERROR_PREFIX.NETWORK}010`,
} as const;

/**
 * 存储相关错误代码
 * 错误代码格式：ERR_STORAGE_XXX，其中XXX为三位数字序号
 */
export const STORAGE_ERRORS = {
  STORAGE_ERROR: `${ERROR_PREFIX.STORAGE}001`,
  STORAGE_NOT_FOUND: `${ERROR_PREFIX.STORAGE}002`,
  STORAGE_READ_FAILED: `${ERROR_PREFIX.STORAGE}003`,
  STORAGE_WRITE_FAILED: `${ERROR_PREFIX.STORAGE}004`,
  STORAGE_DELETE_FAILED: `${ERROR_PREFIX.STORAGE}005`,
  STORAGE_CAPACITY_EXCEEDED: `${ERROR_PREFIX.STORAGE}006`,
  STORAGE_PERMISSION_DENIED: `${ERROR_PREFIX.STORAGE}007`,
} as const;

/**
 * 安全相关错误代码
 * 错误代码格式：ERR_SEC_XXX，其中XXX为三位数字序号
 */
export const SECURITY_ERRORS = {
  SECURITY_ERROR: `${ERROR_PREFIX.SECURITY}001`,
  SECURITY_POLICY_VIOLATED: `${ERROR_PREFIX.SECURITY}002`,
  SECURITY_INPUT_SANITIZATION_FAILED: `${ERROR_PREFIX.SECURITY}003`,
  SECURITY_XSS_DETECTED: `${ERROR_PREFIX.SECURITY}004`,
  SECURITY_CSRF_DETECTED: `${ERROR_PREFIX.SECURITY}005`,
  SECURITY_SQL_INJECTION_DETECTED: `${ERROR_PREFIX.SECURITY}006`,
  SECURITY_RATE_LIMIT_BYPASS_DETECTED: `${ERROR_PREFIX.SECURITY}007`,
} as const;

/**
 * 中间件相关错误代码
 * 错误代码格式：ERR_MW_XXX，其中XXX为三位数字序号
 */
export const MIDDLEWARE_ERRORS = {
  MIDDLEWARE_ERROR: `${ERROR_PREFIX.MIDDLEWARE}001`,
  MIDDLEWARE_NOT_FOUND: `${ERROR_PREFIX.MIDDLEWARE}002`,
  MIDDLEWARE_EXECUTION_FAILED: `${ERROR_PREFIX.MIDDLEWARE}003`,
  MIDDLEWARE_NOT_APPLICABLE: `${ERROR_PREFIX.MIDDLEWARE}004`,
} as const;

/**
 * 插件相关错误代码
 * 错误代码格式：ERR_PLUGIN_XXX，其中XXX为三位数字序号
 */
export const PLUGIN_ERRORS = {
  PLUGIN_NOT_FOUND: `${ERROR_PREFIX.PLUGIN}001`,
  PLUGIN_LOAD_FAILED: `${ERROR_PREFIX.PLUGIN}002`,
  PLUGIN_UNLOAD_FAILED: `${ERROR_PREFIX.PLUGIN}003`,
  PLUGIN_INITIALIZATION_FAILED: `${ERROR_PREFIX.PLUGIN}004`,
  PLUGIN_DEPENDENCY_MISSING: `${ERROR_PREFIX.PLUGIN}005`,
  PLUGIN_VERSION_INCOMPATIBLE: `${ERROR_PREFIX.PLUGIN}006`,
  PLUGIN_ALREADY_LOADED: `${ERROR_PREFIX.PLUGIN}007`,
} as const;

/**
 * 错误消息模板
 * 支持参数插值的错误消息模板定义
 */
export const ERROR_MESSAGES = {
  MODEL_NOT_FOUND: '模型 "{model}" 未找到或不可用',
  MODEL_INVOCATION_FAILED: '模型调用失败：{reason}',
  TOOL_NOT_FOUND: '工具 "{tool}" 未找到',
  TOOL_EXECUTION_FAILED: '工具 "{tool}" 执行失败：{reason}',
  TOOL_TIMEOUT: '工具 "{tool}" 执行超时（{timeout}ms）',
  EXECUTION_TIMEOUT: '执行超时（{timeout}ms）',
  EXECUTION_STEPS_EXCEEDED: '执行步数超过限制（{maxSteps}步）',
  EXECUTION_CANCELLED: '执行被取消',
  AUTH_FAILED: '认证失败：{reason}',
  AUTH_TOKEN_EXPIRED: '认证令牌已过期',
  RATE_LIMIT_EXCEEDED: '请求频率超限，请稍后重试',
  TOKEN_LIMIT_EXCEEDED: 'Token使用量超限（{used}/{limit}）',
  VALIDATION_FAILED: '数据验证失败：{details}',
  CONFIG_NOT_FOUND: '配置项 "{key}" 未找到',
  CIRCUIT_BREAKER_OPEN: '服务暂时不可用（断路器已开启）',
  NETWORK_ERROR: '网络错误：{reason}',
  INTERNAL_ERROR: '内部错误：{reason}',
  UNKNOWN_ERROR: '未知错误：{reason}',
} as const;

/**
 * 错误严重级别
 */
export const ERROR_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

/**
 * 错误恢复策略
 */
export const ERROR_RECOVERY_STRATEGY = {
  NONE: 'none',
  RETRY: 'retry',
  FALLBACK: 'fallback',
  CIRCUIT_BREAKER: 'circuit_breaker',
  DEGRADE: 'degrade',
  NOTIFY: 'notify',
} as const;

/**
 * 导出所有错误相关常量的统一类型
 */
export type HTTPStatusCode = typeof HTTP_STATUS[keyof typeof HTTP_STATUS];
export type ErrorPrefix = typeof ERROR_PREFIX[keyof typeof ERROR_PREFIX];
export type ErrorSeverity = typeof ERROR_SEVERITY[keyof typeof ERROR_SEVERITY];
export type ErrorRecoveryStrategy = typeof ERROR_RECOVERY_STRATEGY[keyof typeof ERROR_RECOVERY_STRATEGY];

/**
 * 组合所有错误代码常量
 */
export const ALL_ERROR_CODES = {
  ...MODEL_ERRORS,
  ...TOOL_ERRORS,
  ...EXECUTION_ERRORS,
  ...AUTH_ERRORS,
  ...RATE_LIMIT_ERRORS,
  ...TIMEOUT_ERRORS,
  ...VALIDATION_ERRORS,
  ...CONFIG_ERRORS,
  ...CIRCUIT_BREAKER_ERRORS,
  ...RETRY_ERRORS,
  ...NETWORK_ERRORS,
  ...STORAGE_ERRORS,
  ...SECURITY_ERRORS,
  ...MIDDLEWARE_ERRORS,
  ...PLUGIN_ERRORS,
} as const;

export type AllErrorCodes = typeof ALL_ERROR_CODES[keyof typeof ALL_ERROR_CODES];
